import { EcommerceProfitInputs, EcommerceProfitResults } from '../types/ecommerce';

export function generateEcommerceCsv(
  inputs: EcommerceProfitInputs,
  results: EcommerceProfitResults
): string {
  const fmt = (n: number | null | undefined) => (n !== null && n !== undefined && !isNaN(n) ? n.toFixed(2) : '0.00');
  const rows: [string, string][] = [
    ['E-COMMERCE INVESTMENT & PROFIT BREAKDOWN REPORT', ''],
    ['Generated By', 'ProfitEbay E-commerce Calculator'],
    ['Report Date', new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })],
    ['', ''],
    ['--- SOURCING & INITIAL INVENTORY CAPITAL ---', ''],
    ['Batch Units Purchased', inputs.unitsPurchased.toString()],
    ['Product Unit Sourcing Cost', `$${fmt(inputs.productCostPerUnit)}`],
    ['Total Product Purchase Cost', `$${fmt(results.totalProductCost)}`],
    ['Inbound Freight / Shipping', `$${fmt(inputs.shippingFreight)}`],
    ['Customs / Import Duties', `$${fmt(inputs.customsDuties)}`],
    ['Other Sourcing & Handling Fees', `$${fmt(inputs.otherImportCosts)}`],
    ['TOTAL INITIAL INVENTORY OUTLAY', `$${fmt(results.totalLandedInventoryCost)}`],
    ['LANDED COST PER UNIT', `$${fmt(results.landedCostPerUnit)}`],
    ['', ''],
    ['--- PRICING & MONTHLY SALES VELOCITY ---', ''],
    ['Selling Price Per Unit', `$${fmt(inputs.sellingPricePerUnit)}`],
    ['Expected Monthly Units Sold', inputs.monthlyUnitsSold.toString()],
    ['Gross Monthly Revenue', `$${fmt(results.monthlyRevenue)}`],
    ['', ''],
    ['--- MONTHLY OPERATING EXPENSES ---', ''],
    ['Monthly Product Cost (COGS)', `$${fmt(results.monthlyProductCost)}`],
    [
      `Marketplace Channel Fees (${inputs.marketplaceFeeType === 'percentage' ? inputs.marketplaceFeeValue + '%' : '$' + fmt(inputs.marketplaceFeeValue) + '/unit'})`,
      `$${fmt(results.marketplaceFees)}`
    ],
    [
      `Payment Processing Fees (${inputs.paymentProcessingFeeType === 'percentage' ? inputs.paymentProcessingFeeValue + '%' : '$' + fmt(inputs.paymentProcessingFeeValue) + '/mo'})`,
      `$${fmt(results.paymentProcessingFees)}`
    ],
    [
      `Advertising / PPC Spend (${inputs.advertisingFeeType === 'percentage' ? inputs.advertisingFeeValue + '%' : '$' + fmt(inputs.advertisingFeeValue) + '/mo'})`,
      `$${fmt(results.advertisingCost)}`
    ],
    ['Packaging Supplies ($/unit)', `$${fmt(results.packagingCost)}`],
    ['Fixed Monthly Overhead & Tools', `$${fmt(results.otherMonthlyExpenses)}`],
    ['TOTAL MONTHLY EXPENSES', `$${fmt(results.totalMonthlyExpenses)}`],
    ['', ''],
    ['--- PROFITABILITY & CAPITAL RETURNS ---', ''],
    ['NET MONTHLY PROFIT', `$${fmt(results.netProfit)}`],
    ['Profit Margin (%)', results.profitMargin !== null ? `${results.profitMargin.toFixed(2)}%` : 'N/A'],
    ['Monthly ROI (%)', results.roi !== null ? `${results.roi.toFixed(2)}%` : 'N/A'],
    ['Annualized Simple ROI (%)', results.annualizedRoi !== null ? `${results.annualizedRoi.toFixed(2)}%` : 'N/A'],
    ['Profitability Status', results.profitabilityStatus],
    ['', ''],
    ['--- UNIT ECONOMICS & BREAK-EVEN INTELLIGENCE ---', ''],
    ['Unit Contribution Margin', `$${fmt(results.contributionMarginPerUnit)} / unit`],
    ['Operating Break-Even Sales (Monthly)', results.operatingBreakEvenUnits !== null ? `${results.operatingBreakEvenUnits} units/month` : 'Unreachable'],
    ['Operating Break-Even Monthly Revenue', results.operatingBreakEvenRevenue !== null ? `$${fmt(results.operatingBreakEvenRevenue)}` : 'Unreachable'],
    ['Capital Recovery Units (Total Units to Recoup Inventory)', results.capitalRecoveryUnits !== null ? `${results.capitalRecoveryUnits} units` : 'N/A'],
    ['Capital Payback Timeline', results.monthsToRecoverInvestment !== null ? `${results.monthsToRecoverInvestment.toFixed(1)} months` : 'Negative Cashflow'],
  ];

  return rows.map(([col1, col2]) => `"${col1.replace(/"/g, '""')}","${col2.replace(/"/g, '""')}"`).join('\n');
}

export function downloadEcommerceCsv(
  inputs: EcommerceProfitInputs,
  results: EcommerceProfitResults,
  filename = 'ecommerce-investment-profit-breakdown.csv'
): void {
  const csvContent = generateEcommerceCsv(inputs, results);
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function printEcommercePdfReport(
  inputs: EcommerceProfitInputs,
  results: EcommerceProfitResults
): void {
  const fmt = (n: number) => '$' + n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to generate and export your PDF report.');
    return;
  }

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>E-commerce Investment & Profit Report - ProfitEbay</title>
  <style>
    @page {
      size: A4 portrait;
      margin: 15mm 15mm 15mm 15mm;
    }
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      color: #1e293b;
      background: #ffffff;
      line-height: 1.45;
      font-size: 13px;
      padding: 24px;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 2px solid #0f172a;
      padding-bottom: 16px;
      margin-bottom: 20px;
    }
    .logo-title {
      font-size: 22px;
      font-weight: 800;
      color: #0f172a;
      letter-spacing: -0.02em;
    }
    .logo-sub {
      font-size: 12px;
      color: #64748b;
      font-weight: 500;
      margin-top: 2px;
    }
    .meta-info {
      text-align: right;
      font-size: 11px;
      color: #64748b;
    }
    .highlight-banner {
      background: #0f172a;
      color: #ffffff;
      border-radius: 8px;
      padding: 16px 20px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 24px;
    }
    .hero-stat-label {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: #94a3b8;
    }
    .hero-stat-val {
      font-size: 28px;
      font-weight: 800;
      color: ${results.netProfit >= 0 ? '#4ade80' : '#f87171'};
      letter-spacing: -0.02em;
    }
    .hero-grid {
      display: flex;
      gap: 24px;
    }
    .hero-pill {
      text-align: right;
    }
    .hero-pill-val {
      font-size: 16px;
      font-weight: 700;
      color: #ffffff;
    }
    .grid-2 {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
      margin-bottom: 20px;
    }
    .card {
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 14px 16px;
      background: #fafafa;
    }
    .card-title {
      font-size: 12px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #334155;
      margin-bottom: 12px;
      padding-bottom: 6px;
      border-bottom: 1px solid #e2e8f0;
    }
    .table-ledger {
      width: 100%;
      border-collapse: collapse;
      font-size: 12px;
    }
    .table-ledger tr td {
      padding: 5px 0;
      border-bottom: 1px solid #f1f5f9;
    }
    .table-ledger tr:last-child td {
      border-bottom: none;
    }
    .table-ledger td.val {
      text-align: right;
      font-weight: 600;
      color: #0f172a;
    }
    .table-ledger tr.total-row td {
      border-top: 1.5px solid #cbd5e1;
      border-bottom: none;
      padding-top: 8px;
      font-weight: 700;
      font-size: 13px;
    }
    .status-badge {
      display: inline-block;
      padding: 3px 8px;
      border-radius: 9999px;
      font-size: 10px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      background: ${results.profitabilityStatus === 'PROFITABLE' ? '#dcfce7' : results.profitabilityStatus === 'BREAK-EVEN' ? '#fef9c3' : '#fee2e2'};
      color: ${results.profitabilityStatus === 'PROFITABLE' ? '#166534' : results.profitabilityStatus === 'BREAK-EVEN' ? '#854d0e' : '#991b1b'};
    }
    .footer-note {
      margin-top: 24px;
      padding-top: 12px;
      border-top: 1px solid #e2e8f0;
      font-size: 10px;
      color: #94a3b8;
      display: flex;
      justify-content: space-between;
    }
    @media print {
      body {
        padding: 0;
      }
      .no-print {
        display: none;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo-title">PROFIT<span style="color:#2563eb">EBAY</span></div>
      <div class="logo-sub">E-commerce Investment & Profit Financial Analysis</div>
    </div>
    <div class="meta-info">
      <div><strong>Date:</strong> ${dateStr}</div>
      <div><strong>Status:</strong> <span class="status-badge">${results.profitabilityStatus}</span></div>
    </div>
  </div>

  <div class="highlight-banner">
    <div>
      <div class="hero-stat-label">Net Monthly Cash Profit</div>
      <div class="hero-stat-val">${fmt(results.netProfit)}</div>
      <div style="font-size:11px;color:#94a3b8;margin-top:2px">Velocity: ${inputs.monthlyUnitsSold} units / month @ ${fmt(inputs.sellingPricePerUnit)}</div>
    </div>
    <div class="hero-grid">
      <div class="hero-pill">
        <div class="hero-stat-label">Net Profit Margin</div>
        <div class="hero-pill-val">${results.profitMargin !== null ? results.profitMargin.toFixed(1) + '%' : 'N/A'}</div>
      </div>
      <div class="hero-pill">
        <div class="hero-stat-label">Monthly ROI</div>
        <div class="hero-pill-val">${results.roi !== null ? results.roi.toFixed(1) + '%' : 'N/A'}</div>
      </div>
      <div class="hero-pill">
        <div class="hero-stat-label">Annualized ROI</div>
        <div class="hero-pill-val">${results.annualizedRoi !== null ? results.annualizedRoi.toFixed(1) + '%' : 'N/A'}</div>
      </div>
    </div>
  </div>

  <div class="grid-2">
    <!-- Capital Outlay & Landed Costs -->
    <div class="card">
      <div class="card-title">1. Sourcing & Initial Inventory Outlay</div>
      <table class="table-ledger">
        <tr>
          <td>Units Purchased (Batch Size)</td>
          <td class="val">${inputs.unitsPurchased.toLocaleString()} units</td>
        </tr>
        <tr>
          <td>Supplier Unit Cost</td>
          <td class="val">${fmt(inputs.productCostPerUnit)}</td>
        </tr>
        <tr>
          <td>Total Product Purchase Cost</td>
          <td class="val">${fmt(results.totalProductCost)}</td>
        </tr>
        <tr>
          <td>Ocean / Air Freight</td>
          <td class="val">${fmt(inputs.shippingFreight)}</td>
        </tr>
        <tr>
          <td>Customs & Tariffs</td>
          <td class="val">${fmt(inputs.customsDuties)}</td>
        </tr>
        <tr>
          <td>Port & Handling Fees</td>
          <td class="val">${fmt(inputs.otherImportCosts)}</td>
        </tr>
        <tr class="total-row">
          <td>Total Initial Inventory Outlay</td>
          <td class="val" style="color:#0f172a">${fmt(results.totalLandedInventoryCost)}</td>
        </tr>
        <tr>
          <td style="color:#2563eb;font-weight:600">True Landed Cost Per Unit</td>
          <td class="val" style="color:#2563eb">${fmt(results.landedCostPerUnit)}</td>
        </tr>
      </table>
    </div>

    <!-- Monthly Operating Expenses & COGS -->
    <div class="card">
      <div class="card-title">2. Monthly P&L Operating Expenses</div>
      <table class="table-ledger">
        <tr>
          <td style="color:#16a34a;font-weight:600">Gross Monthly Revenue</td>
          <td class="val" style="color:#16a34a">+${fmt(results.monthlyRevenue)}</td>
        </tr>
        <tr>
          <td>Product COGS (${inputs.monthlyUnitsSold} units sold)</td>
          <td class="val">-${fmt(results.monthlyProductCost)}</td>
        </tr>
        <tr>
          <td>Marketplace Selling Fees</td>
          <td class="val">-${fmt(results.marketplaceFees)}</td>
        </tr>
        <tr>
          <td>Payment Processing Fees</td>
          <td class="val">-${fmt(results.paymentProcessingFees)}</td>
        </tr>
        <tr>
          <td>Advertising / PPC Spend</td>
          <td class="val">-${fmt(results.advertisingCost)}</td>
        </tr>
        <tr>
          <td>Packaging Supplies</td>
          <td class="val">-${fmt(results.packagingCost)}</td>
        </tr>
        <tr>
          <td>Fixed Monthly Overhead & Tools</td>
          <td class="val">-${fmt(results.otherMonthlyExpenses)}</td>
        </tr>
        <tr class="total-row">
          <td>Total Monthly Expenses</td>
          <td class="val" style="color:#dc2626">-${fmt(results.totalMonthlyExpenses)}</td>
        </tr>
      </table>
    </div>
  </div>

  <!-- Intelligence & Payback Section -->
  <div class="card" style="margin-bottom:16px">
    <div class="card-title">3. Unit Economics & Capital Payback Analysis</div>
    <table class="table-ledger">
      <tr>
        <td><strong>Unit Contribution Margin</strong> (Selling Price − Variable Costs per Unit)</td>
        <td class="val" style="color:${results.contributionMarginPerUnit > 0 ? '#16a34a' : '#dc2626'}">
          ${fmt(results.contributionMarginPerUnit)} / unit
        </td>
      </tr>
      <tr>
        <td><strong>Operating Break-Even Volume</strong> (Monthly sales to cover $${results.otherMonthlyExpenses.toFixed(2)} fixed overhead)</td>
        <td class="val">
          ${results.operatingBreakEvenUnits !== null ? `${results.operatingBreakEvenUnits} units/mo (${fmt(results.operatingBreakEvenRevenue || 0)}/mo)` : 'Unreachable'}
        </td>
      </tr>
      <tr>
        <td><strong>Capital Recovery Units</strong> (Cumulative sales to recoup $${results.totalLandedInventoryCost.toFixed(2)} initial inventory)</td>
        <td class="val">
          ${results.capitalRecoveryUnits !== null ? `${results.capitalRecoveryUnits.toLocaleString()} units total` : 'N/A'}
        </td>
      </tr>
      <tr>
        <td><strong>Capital Payback Timeline</strong> (Months to recoup initial inventory from net monthly cash profit)</td>
        <td class="val">
          ${results.monthsToRecoverInvestment !== null ? `${results.monthsToRecoverInvestment.toFixed(1)} Months` : 'Negative Cashflow'}
        </td>
      </tr>
    </table>
  </div>

  <div class="footer-note">
    <span>Report generated via ProfitEbay E-commerce Financial Suite</span>
    <span>https://profitebay.com/ecommerce-investment-profit-calculator</span>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 300);
    };
  </script>
</body>
</html>
`;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}
